# server
server:
  port: 8085

# spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.2:3306/spring_demo_db?useUnicode=true?characterEncoding=UTF-8?serverTimezone=GMT%2B8
    username: root
    password: 123456
  application:
    name: spring-web-demo

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

# log
logging:
  config: classpath:logback-spring.xml
